### ISSUE TITLE
.project im git repository

### ISSUE THREAD

**Issue by LineF** [trilu2000/NewAskSin#18]
Seit einem der letzten Commits im Branch DevAES kommt jetzt die .project Datei mit.
Dies ist allerdings sehr hinderlich bei der Integration der Commits in das eigene Repository, da damit die eigene Projektverwaltung durcheinander kommt. Die Datei ist zudem geöffnet, so daß ein Merge daran scheitert (stashen/reset etc funktioniert nicht).

Martin

**Comment by kc-GitHub** [comment]
Ich hab die Datei mal gelöscht und in .gitignore mit aufgenommen.
