### ISSUE TITLE
cmblind.cpp is broken (contains patch elements)

### ISSUE THREAD

**Issue by viegener** [trilu2000/NewAskSin#9]
Hallo,
in cmBlind.cc sind patch-diffs enthalten, damit geht die Compilation der Lib schief:

Bsp - Zeile 9 folgende:

<<<<<<< HEAD
# //#define BL_DBG                                                                            // debug message flag

//#define DI_DBG                                                                            // debug message flag

> > > > > > > origin/master

**Comment by kc-GitHub** [comment]
Danke. Ich hab's mal gefixt.
